# Bernoulli random experiment 

An experiment is called a Bernoulli distribution if it meets the following conditions:

1.	The experiment consists of two outcomes: the outcome of interest (commonly called “success”) and the outcome not of interest (commonly called “failure”).
2.	The experiment is performed only once


In [1]:
#For example, toss one coin with a success probability of 50%

from scipy.stats import bernoulli
bernoulli.rvs(p=0.5, size = 1)

array([1], dtype=int64)

In [2]:
#Note: 
#p = probability of success
#size = number of coins tossed


In [3]:
#For example, change the number of coins tossed to 10
from scipy.stats import bernoulli
bernoulli.rvs(p=0.5, size = 10)

array([0, 1, 0, 1, 0, 1, 0, 0, 1, 1], dtype=int64)

In [4]:
#To count the number of heads or tails that appear 
#How many heads
sum(bernoulli.rvs(p=0.5, size = 10))

6

In [5]:
#another draw

sum(bernoulli.rvs(p=0.5, size = 10))

5

## Binomial random variable


In [6]:
#For example, toss one coin 10 times with a success probability of 50%.
from scipy.stats import binom
binom.rvs(n=10, p=0.5, size=1)

array([5], dtype=int64)

In [7]:
#Note: 
#n = number of trials
#p = probability of success 
#size = number of coins tossed

In [8]:
# For example, toss 10 coins in 10 trials with a success probability of 50%.
from scipy.stats import binom
binom.rvs(n=10, p=0.5, size=10)

array([8, 4, 4, 5, 5, 4, 4, 9, 4, 3], dtype=int64)

### Random generator seed


In [9]:
from scipy.stats import binom
import numpy as np
np.random.seed(42)
binom.rvs(n=10, p=0.5, size=1)

array([4], dtype=int64)

In [10]:
from scipy.stats import binom
np.random.seed(42)
binom.rvs(n=10, p=0.5, size=1)

array([4], dtype=int64)

## Probability mass and distribution functions

### Probability mass functions

In [11]:
#For example, find the probability of getting exactly 2 heads in 10 trials 
#dan peluang berhasil sebanyak 50%.

# Probability of 2 heads after 10 throws with a fair coin
from scipy.stats import binom
binom.pmf(k = 2, n = 10, p = 0.5)

0.04394531250000005

In [12]:
#For example, find the probability of getting exactly 5 heads in 10 trials 
# and success probability of 50%.

# Probability of 2 heads after 10 throws with a fair coin
from scipy.stats import binom
binom.pmf(k = 5, n = 10, p = 0.5)

0.24609375

In [13]:
#For example, find the probability of getting exactly 50 heads in 100 trials 
# and success probability of 30%.

# Probability of 50 heads after 100 throws with p=0.3

from scipy.stats import binom
binom.pmf(k = 50, n = 100, p = 0.3)

1.3026227131445274e-05

In [14]:
# For example, find the probability of getting exactly 65 heads in 100 trials
# with a success probability of 70%.

from scipy.stats import binom
binom.pmf(k = 65, n = 100, p = 0.7)

0.046779682352730015

### Cumulative distribution function (cdf) 

### To find the probability of getting less than

In [15]:
#For example, find the probability of getting 5 or fewer heads in 10 trials 
# and success probability of 50%.

# Probability of 5 heads or less after 10 throws with a fair coin
from scipy.stats import binom
binom.cdf(k = 5, n = 10, p = 0.5)

0.623046875

In [16]:
#For example, find the probability of getting 50 or fewer heads in 100 trials 
# and success probability of 30%.

# Probability of 50 heads or less after 100 throws with p=0.3
from scipy.stats import binom
binom.cdf(k=50, n=100, p=0.3)

0.9999909653138043

### To find the probability of getting more than

In [17]:
#For example, find the probability of getting more than 59 heads in 100 trials 
# and success probability of 70%.

# Probability of more than 59 heads after 100 throws with p=0.7
1-binom.cdf(k=59,n=100,p=0.7)

0.9875015928335618

### Expected Value  

Expected value of a random variable represents the average outcome expected from a random experiment, or the tendency of results that will occur.

### Arithmetic mean

In Python, we use scipy.stats.describe() to obtain the arithmetic mean.

In [18]:
# For example, find the mean of 0 and 1
from scipy.stats import describe
describe([0,1]).mean

0.5

## Variance

Variance is used to describe the spread of a distribution around its center. The expected value does not explain the shape or variability of a distribution.

In Python, we use scipy.stats.describe() to obtain the variance.

In [19]:
from scipy.stats import describe
describe ([0,1]).variance

0.5

# Binomial distribution expected value and variance

In Python, we use binom.stats() to obtain the mean and variance of the binomial distribution

E(X) = n × p


Var(X) = n × p × (1 − p)

In [20]:
#Using Python
from scipy.stats import binom
binom.stats(n=10, p = 0.5)

(5.0, 2.5)

In [21]:
#For example, find the expected value and variance for one trial with p = 0.3
from scipy.stats import binom
binom.stats(n=1, p = 0.3)

(0.3, 0.21)

In [22]:
#For example, find the expected value and variance for ten trials with p = 0.5
from scipy.stats import binom
binom.stats(n=10, p = 0.5)

(5.0, 2.5)